~ 01-20 `Exercise`: Nearby Friends (`Python 3.10`) ~
$ NOTE:
  We `don't "append"` to sets because appending means "adding at the end".
  Since `sets don't have order`, there is no "end" to add to! :wink:

> AttributeError: 'set' object has no attribute 'append' <-- LOOK!
$ art_friends.append("Vladimir")  # ERROR !!!

> So, instead of `append`, there is method called `add` for adding element
  to the set [duplicate element is NOT added to that set!]. :electric_plug: :brain:
$ art_friends.add("Vladimir")